# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  time_zone: "America/Detroit"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml

script: !include scripts.yaml

scene: !include scenes.yaml

sensor: !include sensors.yaml

template: !include templates.yaml